sudo: required
language: node_js
node_js:
  - lts/*
env:
  global:
    - HOST=myHost
cache:
directories:
  - node_modules
addons:
  ssh_known_hosts: $HOST
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - npm ci
script:
  - npm run build
before_deploy:
  - tar -czf covidmaps.media-$TRAVIS_TAG.tar.gz covidmaps.media
  - zip -r covidmaps.media-$TRAVIS_TAG.zip covidmaps.media
  - ls -al
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/covidmaps.media web@$HOST:/var/www/
    on:
      branch: master
      repo: Boogst/CovidMap-web
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: 
      - covidmaps.media-$TRAVIS_TAG.tar.gz
      - covidmaps.media-$TRAVIS_TAG.zip
    skip_cleanup: true
    on:
      tags: true
      branch: master
      repo: Boogst/covidmaps-full-stack-application