sudo: required
language: node_js
node_js:
- lts/*
env:
  global:
    - HOST=myHost
cache: 
directories:
- node_modules
addons:
    ssh_known_hosts: $HOST
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- npm ci
script:
- npm run build
before_deploy:
- ls
deploy:
  provider: script
  api_key: "$GITHUB_TOKEN"
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/api.covidmaps.media/server.js web@$HOST:/var/www/api.covidmaps.media/
  skip_cleanup: true
  on:
    repo: Boogst/covidmaps-full-stack-application
